# Generated by Django 5.2.5 on 2025-09-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paciente',
            name='pacientes_p_numero__485b0f_idx',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='numero_documento',
            new_name='dni',
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['dni'], name='pacientes_p_dni_722873_idx'),
        ),
    ]
