# Generated by Django 5.2.5 on 2025-09-18 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analitos', '0001_initial'),
        ('registrar_examenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoAnalito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('alto', 'Alto'), ('bajo', 'Bajo'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('analito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analitos.analito')),
                ('registro_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar_examenes.registroexamen')),
            ],
        ),
    ]
