# Generated by Django 5.2.5 on 2025-09-18 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('igv', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.tipoexamen')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('igv', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.tipoexamen')),
            ],
        ),
    ]
