# Generated by Django 5.2.5 on 2025-09-18 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrar_examenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('registro_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrar_examenes.registroexamen')),
            ],
        ),
    ]
